### PR TITLE
Added Unknown Screen. Fixes Issue #161

### LINKED ISSUE #161: App is using a Text Widget for unknown route instead of a screen.
# Bug Report 🐛
If by chance there is no valid route, user must be navigated to a screen, rather than encountering app crash or errors, but the app is using a Text widget instead of a screen.

## Expected Behavior
If there is no valid route or screen, user must be navigated to a screen saying, unknown route.

## Current Behavior
A black screen, with a text is shown.

## Possible Solution
I will create a new screen, create its route constant and use it in the route_page.dart file as a default case. 

I am the participant of GSSOC 21. Please assign me this issue.

### PR DESCRIPTION
**Pull request by SapinderSingh**
### Related Issue
- Fixes #161 .

### Proposed Changes
- Added Unknown Screen.
- Created route constant for the screen in constants.dart.
- Linked route for the screen in default case in route_page.dart

### Checklist
- [X] Tested
- [X] No Conflicts
- [X] Change In Code
- [X] Follows linting rules
WhatsApp Image 2021-03-26 at 12 05 28

### CODE REVIEW

File: lib/helpers/constants.dart [hunk 1]
```diff
@@ -23,6 +23,7 @@ class RouteConstant {
   static const String TERMS_CONDITIONS = '/terms-conditions';
   static const String PAYMENT_SUCCESSFULL = '/payment-successful';
   static const String CHANGE_USERNAME_SCREEN = '/change_username';
+  static const String UNKNOWN_VIEW = '/unknown-view';
```
Comment (himanshusharma89) [inline lib/helpers/constants.dart:26]: Do we need this here? I don't see its use case.

**Review by himanshusharma89 — CHANGES_REQUESTED** [review]

File: lib/helpers/constants.dart (hunk 1 above)
Comment (SapinderSingh) [reply lib/helpers/constants.dart]: Fixed!
