### PR TITLE
Fixes #217

### LINKED ISSUE #217: name getter was called on null.
# Bug Report 🐛
When user tries to login, The home screen shows a exception that name getter was called on null. It is because, the dashboard is not waiting to complete the future(get user method) and sending the userinfo to homescreen. 

## Possible Solution
It's solution is to use, FutureBuilder, we will show a Circular Indicator till the future completes and then show the homescreen.

## Steps to Reproduce
1. Clear the data of the app.
2.  Login with google. 
3. You will see the error.

## Video -
https://user-images.githubusercontent.com/29424616/116799359-4fb7ae00-ab16-11eb-862e-140c43370fff.mp4

## Exception in console - 
image

I want to solve this issue as a participant of GSSOC 21.

### PR DESCRIPTION
**Pull request by SapinderSingh**
### Related Issue
- Fixes #217 .

### Proposed Changes
- Used FutureBuilder

### Checklist
- [X] Tested
- [X] No Conflicts
- [X] Change In Code
- [ ] Change In Documentation
- [X] Follows linting rules

https://user-images.githubusercontent.com/29424616/116803731-e34da680-ab37-11eb-9754-eab7f70d0ca4.mp4

### CODE REVIEW

File: lib/dashboard.dart [hunk 1]
```diff
@@ -69,25 +68,37 @@ class _DashboardState extends State<Dashboard> {
...
-                ),
-                Search(),
-                Cart(
-                  pageController: _pageController,
-                ),
-                ProfilePage(user: userinfo,)
-              ],
-            ),
+            FutureBuilder<UserModel>(
+                future: getUser(),
```
Comment (himanshusharma89) [inline lib/dashboard.dart:72]: This will have a repetitive call in build method

**Comment by himanshusharma89** [comment]
I'll currently merge this PR, creating new issue to handle the user with Provider or SharedPref
